workflows:
  android-debug-apk:
    name: Android debug APK
    instance_type: linux_x2
    max_build_duration: 30
    environment:
      flutter: stable
      java: 17
    caching:
      cache_paths:
        - $HOME/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Analyze
        script: flutter analyze
      - name: Test
        script: flutter test
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

  android-release-apk:
    name: Android release APK
    instance_type: linux_x2
    max_build_duration: 30
    environment:
      flutter: stable
      java: 17
    caching:
      cache_paths:
        - $HOME/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Analyze
        script: flutter analyze
      - name: Test
        script: flutter test
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
